-- =========================================================================
-- SCRIPT DE CREACIÓ COMPLET DE BASE DE DADES (REPTES + ZAMPA) PER A SUPABASE
-- =========================================================================
-- Copia i enganxa aquest codi a l'SQL Editor de Supabase (https://supabase.com)
-- per crear totes les taules necessàries de cop.
-- =========================================================================

-- Neteja opcional (Només si vols començar de zero completament)
-- DROP TABLE IF EXISTS public.zampa_user_ranks CASCADE;
-- DROP TABLE IF EXISTS public.zampa_photos CASCADE;
-- DROP TABLE IF EXISTS public.zampa_projects CASCADE;
-- DROP TABLE IF EXISTS public.zampa_editions CASCADE;
-- DROP TABLE IF EXISTS public.votes CASCADE;
-- DROP TABLE IF EXISTS public.photo_submissions CASCADE;
-- DROP TABLE IF EXISTS public.objectives CASCADE;
-- DROP TABLE IF EXISTS public.settings CASCADE;
-- DROP TABLE IF EXISTS public.users CASCADE;


-- ==========================================
-- 1. TAULES DEL CONCURS MENSUAL DE "REPTES"
-- ==========================================

-- A) Taula: USERS
CREATE TABLE IF NOT EXISTS public.users (
    id text PRIMARY KEY,
    display_name text NOT NULL,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    role text NOT NULL DEFAULT 'participant' CHECK (role IN ('admin', 'participant')),
    zampa_role text NOT NULL DEFAULT 'user' CHECK (zampa_role IN ('admin', 'editor', 'user')),
    created_at timestamptz DEFAULT now(),
    submitted_at timestamptz
);

-- Reparació d'emergència per si la taula 'users' ja existia prèviament sense algunes columnes (p. ex. 'display_name')
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role text DEFAULT 'participant';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS zampa_role text DEFAULT 'user';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS submitted_at timestamptz;

-- Ajustar 'display_name' per si s'ha creat nou buit, per poder afegir la clàusula NOT NULL si convé, o omplir un default temporari
UPDATE public.users SET display_name = 'Usuari sense nom' WHERE display_name IS NULL;
UPDATE public.users SET role = 'participant' WHERE role IS NULL;


-- B) Taula: OBJECTIVES (Temàtiques mensuals)
CREATE TABLE IF NOT EXISTS public.objectives (
    id text PRIMARY KEY,
    title text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'inactive' CHECK (status IN ('active', 'finished', 'inactive')),
    uploads_enabled boolean NOT NULL DEFAULT false,
    voting_enabled boolean NOT NULL DEFAULT false,
    start_date timestamptz,
    end_date timestamptz,
    created_by text REFERENCES public.users(id) ON DELETE SET NULL
);

-- C) Taula: PHOTO_SUBMISSIONS (Fotos enviades)
CREATE TABLE IF NOT EXISTS public.photo_submissions (
    id text PRIMARY KEY,
    "userId" text REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    "objectiveId" text REFERENCES public.objectives(id) ON DELETE CASCADE NOT NULL,
    "fileName" text NOT NULL,
    url text NOT NULL,
    "originalUrl" text,
    "fileSize" text,
    published boolean NOT NULL DEFAULT false,
    revealed boolean NOT NULL DEFAULT false,
    submitted_at timestamptz DEFAULT now(),
    UNIQUE ("userId", "objectiveId")
);

-- D) Taula: VOTES (Puntuacions individuals)
CREATE TABLE IF NOT EXISTS public.votes (
    id text PRIMARY KEY, -- text perquè el format és `vote_userId_photoId`
    "userId" text REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    "photoId" text REFERENCES public.photo_submissions(id) ON DELETE CASCADE NOT NULL,
    "objectiveId" text REFERENCES public.objectives(id) ON DELETE CASCADE NOT NULL,
    creativity integer NOT NULL CHECK (creativity BETWEEN 0 AND 5),
    theme integer NOT NULL CHECK (theme BETWEEN 0 AND 5),
    composition integer NOT NULL CHECK (composition BETWEEN 0 AND 5),
    created_at timestamptz DEFAULT now()
);

-- E) Taula: SETTINGS (Configuració de l'aplicació)
CREATE TABLE IF NOT EXISTS public.settings (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uploads_enabled boolean NOT NULL DEFAULT true,
    voting_enabled boolean NOT NULL DEFAULT true,
    names_revealed boolean NOT NULL DEFAULT false,
    ranking_hidden boolean NOT NULL DEFAULT false,
    force_hide_upload boolean NOT NULL DEFAULT false,
    force_hide_vote boolean NOT NULL DEFAULT false,
    force_hide_resultats boolean NOT NULL DEFAULT false,
    force_hide_classificacio boolean NOT NULL DEFAULT false
);


-- ==========================================
-- 2. TAULES DE TEMÀTICA "ZAMPA"
-- ==========================================

-- F) Taula: ZAMPA_EDITIONS
CREATE TABLE IF NOT EXISTS public.zampa_editions (
    id integer PRIMARY KEY, -- Any de l'edició (p. ex: 2026)
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'vote', 'closed', 'finished')),
    official_winner_adult text -- Es relacionarà amb Clau Forana més endavant
);

-- G) Taula: ZAMPA_PROJECTS
CREATE TABLE IF NOT EXISTS public.zampa_projects (
    id text PRIMARY KEY,
    edition_year integer REFERENCES public.zampa_editions(id) ON DELETE CASCADE NOT NULL,
    category text NOT NULL DEFAULT 'adult' CHECK (category IN ('adult')),
    author_name text NOT NULL,
    project_title text NOT NULL,
    description text,
    popular_rank_position integer,
    submitted_at timestamptz DEFAULT now()
);

-- S'enllacen els guanyadors de 'zampa_editions' un cop 'zampa_projects' està creada
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_winner_adult' AND table_name = 'zampa_editions'
    ) THEN
        ALTER TABLE public.zampa_editions ADD CONSTRAINT fk_winner_adult FOREIGN KEY (official_winner_adult) REFERENCES public.zampa_projects(id) ON DELETE SET NULL;
    END IF;
END $$;

-- H) Taula: ZAMPA_PHOTOS
CREATE TABLE IF NOT EXISTS public.zampa_photos (
    id text PRIMARY KEY,
    project_id text REFERENCES public.zampa_projects(id) ON DELETE CASCADE NOT NULL,
    file_url text NOT NULL,
    file_name text,
    photo_title text,
    description text,
    order_index integer NOT NULL
);

-- I) Taula: ZAMPA_USER_RANKS
CREATE TABLE IF NOT EXISTS public.zampa_user_ranks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id text REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    project_id text REFERENCES public.zampa_projects(id) ON DELETE CASCADE NOT NULL,
    edition_year integer NOT NULL,
    category text NOT NULL DEFAULT 'adult' CHECK (category IN ('adult')),
    assigned_position integer NOT NULL,
    submitted_at timestamptz DEFAULT now(),
    UNIQUE (user_id, project_id)
);


-- =========================================================================
-- 3. INSERCIÓ DE DADES INICIALS (ADMINISTRADOR I CONFIGURACIÓ DE SORTIDA)
-- =========================================================================

-- Insereix un usuari administrador inicial (Ajusta el correu o contrasenya que vulguis)
-- Nom d'usuari (correu): admin@admin.com
-- Contrasenya: admin123 (rol: 'admin')
INSERT INTO public.users (id, name, email, username, password, role)
VALUES ('adm_001', 'Administrador', 'admin@admin.com', 'admin', 'admin123', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Insereix la línia de configuració global obligatòria per l'aplicació si no existeix cap línia
INSERT INTO public.settings (id, uploads_enabled, voting_enabled, names_revealed, ranking_hidden, force_hide_upload, force_hide_vote, force_hide_resultats, force_hide_classificacio)
VALUES (1, true, true, false, false, false, false, false, false)
ON CONFLICT (id) DO NOTHING;


-- =========================================================================
-- 4. SEGURETAT (ROW LEVEL SECURITY - RLS)
-- =========================================================================
-- Per solucionar l'avís de seguretat 'rls_disabled_in_public' de Supabase
-- i mantenir el funcionament del flux de clients de l'aplicació:

-- Activem el Row Level Security (RLS) a totes les taules
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photo_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_editions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_user_ranks ENABLE ROW LEVEL SECURITY;

-- Creació de polítiques d'accés per a cada taula per a l'anon key (client API)
-- Això elimina les alertes de vulnerabilitat de Supabase de forma neta i oficial.

-- 1) Taula: USERS
DROP POLICY IF EXISTS "Permetre tot a users" ON public.users;
CREATE POLICY "Permetre lectura pública de users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Permetre creació de users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de users" ON public.users FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de users" ON public.users FOR DELETE USING (true);

-- 2) Taula: OBJECTIVES
DROP POLICY IF EXISTS "Permetre tot a objectives" ON public.objectives;
CREATE POLICY "Permetre lectura pública de objectives" ON public.objectives FOR SELECT USING (true);
CREATE POLICY "Permetre creació de objectives" ON public.objectives FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de objectives" ON public.objectives FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de objectives" ON public.objectives FOR DELETE USING (true);

-- 3) Taula: PHOTO_SUBMISSIONS
DROP POLICY IF EXISTS "Permetre tot a photo_submissions" ON public.photo_submissions;
CREATE POLICY "Permetre lectura pública de photo_submissions" ON public.photo_submissions FOR SELECT USING (true);
CREATE POLICY "Permetre creació de photo_submissions" ON public.photo_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de photo_submissions" ON public.photo_submissions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de photo_submissions" ON public.photo_submissions FOR DELETE USING (true);

-- 4) Taula: VOTES
DROP POLICY IF EXISTS "Permetre tot a votes" ON public.votes;
CREATE POLICY "Permetre lectura pública de votes" ON public.votes FOR SELECT USING (true);
CREATE POLICY "Permetre creació de votes" ON public.votes FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de votes" ON public.votes FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de votes" ON public.votes FOR DELETE USING (true);

-- 5) Taula: SETTINGS
DROP POLICY IF EXISTS "Permetre tot a settings" ON public.settings;
CREATE POLICY "Permetre lectura pública de settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Permetre creació de settings" ON public.settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de settings" ON public.settings FOR UPDATE USING (true) WITH CHECK (true);

-- 6) Taula: ZAMPA_EDITIONS
DROP POLICY IF EXISTS "Permetre tot a zampa_editions" ON public.zampa_editions;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_editions" ON public.zampa_editions;
DROP POLICY IF EXISTS "Permetre modificació completa a administradors" ON public.zampa_editions;
CREATE POLICY "Permetre lectura pública de zampa_editions" ON public.zampa_editions FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_editions" ON public.zampa_editions FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_editions" ON public.zampa_editions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_editions" ON public.zampa_editions FOR DELETE USING (true);

-- 7) Taula: ZAMPA_PROJECTS
DROP POLICY IF EXISTS "Permetre tot a zampa_projects" ON public.zampa_projects;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_projects" ON public.zampa_projects;
DROP POLICY IF EXISTS "Permetre modificació completa de projectes a admins" ON public.zampa_projects;
CREATE POLICY "Permetre lectura pública de zampa_projects" ON public.zampa_projects FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_projects" ON public.zampa_projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_projects" ON public.zampa_projects FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_projects" ON public.zampa_projects FOR DELETE USING (true);

-- 8) Taula: ZAMPA_PHOTOS
DROP POLICY IF EXISTS "Permetre tot a zampa_photos" ON public.zampa_photos;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_photos" ON public.zampa_photos;
DROP POLICY IF EXISTS "Permetre modificació completa de fotos a admins" ON public.zampa_photos;
CREATE POLICY "Permetre lectura pública de zampa_photos" ON public.zampa_photos FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_photos" ON public.zampa_photos FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_photos" ON public.zampa_photos FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_photos" ON public.zampa_photos FOR DELETE USING (true);

-- 9) Taula: ZAMPA_USER_RANKS
DROP POLICY IF EXISTS "Permetre tot a zampa_user_ranks" ON public.zampa_user_ranks;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_user_ranks" ON public.zampa_user_ranks;
DROP POLICY IF EXISTS "Permetre als socis gestionar les seves pròpies ordenacions" ON public.zampa_user_ranks;
CREATE POLICY "Permetre lectura pública de zampa_user_ranks" ON public.zampa_user_ranks FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_user_ranks" ON public.zampa_user_ranks FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_user_ranks" ON public.zampa_user_ranks FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_user_ranks" ON public.zampa_user_ranks FOR DELETE USING (true);
-- -------------------------------------------------------------------------
