-- =========================================================================
-- SCRIPT DE CREACIÓ DE BASE DE DADES — FEM PREMIS ZAMPA (Supabase / PostgreSQL)
-- =========================================================================
-- Copia i enganxa aquest codi a l'SQL Editor del teu projecte Supabase
-- (https://supabase.com) i executa'l per crear totes les taules necessàries.
-- =========================================================================

-- Neteja opcional (només si vols començar de zero completament)
-- DROP TABLE IF EXISTS public.zampa_user_ranks CASCADE;
-- DROP TABLE IF EXISTS public.zampa_photos CASCADE;
-- DROP TABLE IF EXISTS public.zampa_projects CASCADE;
-- DROP TABLE IF EXISTS public.zampa_editions CASCADE;
-- DROP TABLE IF EXISTS public.users CASCADE;


-- ==========================================
-- 1. TAULA: USERS (socis, administradors i editors)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.users (
    id text PRIMARY KEY,
    display_name text NOT NULL,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    role text NOT NULL DEFAULT 'participant' CHECK (role IN ('admin', 'participant')),
    zampa_role text NOT NULL DEFAULT 'user' CHECK (zampa_role IN ('admin', 'editor', 'user')),
    created_at timestamptz DEFAULT now(),
    submitted_at timestamptz
);

-- Reparació d'emergència per si la taula 'users' ja existia prèviament sense alguna columna
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role text DEFAULT 'participant';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS zampa_role text DEFAULT 'user';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS submitted_at timestamptz;

UPDATE public.users SET display_name = 'Usuari sense nom' WHERE display_name IS NULL;
UPDATE public.users SET role = 'participant' WHERE role IS NULL;
UPDATE public.users SET zampa_role = 'user' WHERE zampa_role IS NULL;


-- ==========================================
-- 2. TAULA: ZAMPA_EDITIONS (edicions anuals)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.zampa_editions (
    id integer PRIMARY KEY, -- Any de l'edició (p. ex: 2026)
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'vote', 'closed', 'finished')),
    official_winner_adult text -- Es relacionarà amb clau forana un cop existeixi 'zampa_projects'
);

-- ==========================================
-- 3. TAULA: ZAMPA_PROJECTS (portfolis participants)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.zampa_projects (
    id text PRIMARY KEY,
    edition_year integer REFERENCES public.zampa_editions(id) ON DELETE CASCADE NOT NULL,
    category text NOT NULL DEFAULT 'adult' CHECK (category IN ('adult')),
    author_name text NOT NULL,
    project_title text NOT NULL,
    description text,
    popular_rank_position integer,
    submitted_at timestamptz DEFAULT now()
);

-- S'enllaça el guanyador oficial de 'zampa_editions' un cop 'zampa_projects' ja existeix
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_winner_adult' AND table_name = 'zampa_editions'
    ) THEN
        ALTER TABLE public.zampa_editions ADD CONSTRAINT fk_winner_adult FOREIGN KEY (official_winner_adult) REFERENCES public.zampa_projects(id) ON DELETE SET NULL;
    END IF;
END $$;

-- ==========================================
-- 4. TAULA: ZAMPA_PHOTOS (fotos de cada projecte)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.zampa_photos (
    id text PRIMARY KEY,
    project_id text REFERENCES public.zampa_projects(id) ON DELETE CASCADE NOT NULL,
    file_url text NOT NULL,
    file_name text,
    photo_title text,
    description text,
    order_index integer NOT NULL
);

-- ==========================================
-- 5. TAULA: ZAMPA_USER_RANKS (rànquings enviats pels socis)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.zampa_user_ranks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id text REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    project_id text REFERENCES public.zampa_projects(id) ON DELETE CASCADE NOT NULL,
    edition_year integer NOT NULL,
    category text NOT NULL DEFAULT 'adult' CHECK (category IN ('adult')),
    assigned_position integer NOT NULL,
    submitted_at timestamptz DEFAULT now(),
    UNIQUE (user_id, project_id)
);


-- =========================================================================
-- 6. INSERCIÓ D'UN USUARI ADMINISTRADOR INICIAL
-- =========================================================================
-- Email: admin@admin.com · Contrasenya: admin123 · rol: 'admin' / zampa_role: 'admin'
INSERT INTO public.users (id, display_name, email, password, role, zampa_role)
VALUES ('adm_001', 'Administrador', 'admin@admin.com', 'admin123', 'admin', 'admin')
ON CONFLICT (email) DO NOTHING;


-- =========================================================================
-- 7. SEGURETAT (ROW LEVEL SECURITY - RLS)
-- =========================================================================
-- Per evitar l'avís 'rls_disabled_in_public' de Supabase mantenint el
-- funcionament del client amb la clau anon:

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_editions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zampa_user_ranks ENABLE ROW LEVEL SECURITY;

-- 1) Taula: USERS
DROP POLICY IF EXISTS "Permetre tot a users" ON public.users;
CREATE POLICY "Permetre lectura pública de users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Permetre creació de users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de users" ON public.users FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de users" ON public.users FOR DELETE USING (true);

-- 2) Taula: ZAMPA_EDITIONS
DROP POLICY IF EXISTS "Permetre tot a zampa_editions" ON public.zampa_editions;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_editions" ON public.zampa_editions;
DROP POLICY IF EXISTS "Permetre modificació completa a administradors" ON public.zampa_editions;
CREATE POLICY "Permetre lectura pública de zampa_editions" ON public.zampa_editions FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_editions" ON public.zampa_editions FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_editions" ON public.zampa_editions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_editions" ON public.zampa_editions FOR DELETE USING (true);

-- 3) Taula: ZAMPA_PROJECTS
DROP POLICY IF EXISTS "Permetre tot a zampa_projects" ON public.zampa_projects;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_projects" ON public.zampa_projects;
DROP POLICY IF EXISTS "Permetre modificació completa de projectes a admins" ON public.zampa_projects;
CREATE POLICY "Permetre lectura pública de zampa_projects" ON public.zampa_projects FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_projects" ON public.zampa_projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_projects" ON public.zampa_projects FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_projects" ON public.zampa_projects FOR DELETE USING (true);

-- 4) Taula: ZAMPA_PHOTOS
DROP POLICY IF EXISTS "Permetre tot a zampa_photos" ON public.zampa_photos;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_photos" ON public.zampa_photos;
DROP POLICY IF EXISTS "Permetre modificació completa de fotos a admins" ON public.zampa_photos;
CREATE POLICY "Permetre lectura pública de zampa_photos" ON public.zampa_photos FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_photos" ON public.zampa_photos FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_photos" ON public.zampa_photos FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_photos" ON public.zampa_photos FOR DELETE USING (true);

-- 5) Taula: ZAMPA_USER_RANKS
DROP POLICY IF EXISTS "Permetre tot a zampa_user_ranks" ON public.zampa_user_ranks;
DROP POLICY IF EXISTS "Permetre lectura pública de zampa_user_ranks" ON public.zampa_user_ranks;
DROP POLICY IF EXISTS "Permetre als socis gestionar les seves pròpies ordenacions" ON public.zampa_user_ranks;
CREATE POLICY "Permetre lectura pública de zampa_user_ranks" ON public.zampa_user_ranks FOR SELECT USING (true);
CREATE POLICY "Permetre creació de zampa_user_ranks" ON public.zampa_user_ranks FOR INSERT WITH CHECK (true);
CREATE POLICY "Permetre actualització de zampa_user_ranks" ON public.zampa_user_ranks FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Permetre eliminació de zampa_user_ranks" ON public.zampa_user_ranks FOR DELETE USING (true);
-- -------------------------------------------------------------------------
